In [39]:
import numpy as np
X = np.array(([2,9],[1,5],[3,6]),dtype=float)
y = np.array(([92],[86],[89]),dtype=float)
print(X)
print("_____________________")
print(y)
print("_____________________")
X = X/np.amax(X, axis=0)
print(X)
print("_____________________")
y = y/100
print(y)

[[2. 9.]
 [1. 5.]
 [3. 6.]]
_____________________
[[92.]
 [86.]
 [89.]]
_____________________
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
_____________________
[[0.92]
 [0.86]
 [0.89]]


In [46]:
class Neural_Network():
    def __init__(self):
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 3
        self.w1 = np.random.randn(self.inputSize,self.hiddenSize)
        print("w1",self.w1)
        self.w2 = np.random.randn(self.hiddenSize,self.outputSize)
        print("w2",self.w2)
    def forward(self,X):
        self.z = np.dot(X,self.w1)
        self.z2 = self.sigmoid(self.z)
        self.z3 = np.dot(self.z2,self.w2)
        o = self.sigmoid(self.z3)
        print(self.z,self.z2,self.z3)
        return 0
    def sigmoid(self,s):
        return 1/(1+np.exp(-s))
    def sigmoidPrime(self,s):
        return s*(1-s)
    def backward(self,X,y,o):
        self.o_error = y-o
        self.o_delta = self.o_error*self.sigmoidPrime(o)
        self.z2_error = self.o_delta.dot(self.w2.T)
        self.z2_delta = self.z2_error*self.sigmoidPrime(self.z2)
        self.w1 += X.T.dot(self.z2_delta)
        self.w2 += self.z2.T.dot(self.o_delta)
    def train(self,X,y):
        o = self.forward(X)
        self.backward(X,y,o)
NN = Neural_Network()
for i in range(1000):
    print("Input:\n"+str(X))
    print("Actual output:\n"+str(y))
    print("Predicted output:\n"+str(NN.forward(X)))
    print("Loss:\n"+str(np.mean(np.square(y-NN.forward(X)))))
    print("\n")
    NN.train(X,y)

w1 [[ 0.076513    1.89644315  1.49283458]
 [ 0.41673518 -0.58760908 -0.8647004 ]]
w2 [[-1.24322415]
 [ 1.18894172]
 [-0.33684218]]
Input:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual output:
[[0.92]
 [0.86]
 [0.89]]
[[0.46774385 0.67668635 0.13052266]
 [0.25702388 0.30569823 0.01722242]
 [0.35433645 1.50470376 0.91636765]] [[0.61484962 0.66299872 0.53258442]
 [0.56390455 0.5758349  0.5043055 ]
 [0.58766876 0.81827498 0.71430141]] [[-0.15552595]
 [-0.18629699]
 [ 0.00167042]]
Predicted output:
0
[[0.46774385 0.67668635 0.13052266]
 [0.25702388 0.30569823 0.01722242]
 [0.35433645 1.50470376 0.91636765]] [[0.61484962 0.66299872 0.53258442]
 [0.56390455 0.5758349  0.5043055 ]
 [0.58766876 0.81827498 0.71430141]] [[-0.15552595]
 [-0.18629699]
 [ 0.00167042]]
Loss:
0.7927


[[0.46774385 0.67668635 0.13052266]
 [0.25702388 0.30569823 0.01722242]
 [0.35433645 1.50470376 0.91636765]] [[0.61484962 0.66299872 0.53258442]
 [0.56390455 0.5758349  0.5043055 ]
 [

 [0.35433645 1.50470376 0.91636765]] [[0.61484962 0.66299872 0.53258442]
 [0.56390455 0.5758349  0.5043055 ]
 [0.58766876 0.81827498 0.71430141]] [[-0.15552595]
 [-0.18629699]
 [ 0.00167042]]
Loss:
0.7927


[[0.46774385 0.67668635 0.13052266]
 [0.25702388 0.30569823 0.01722242]
 [0.35433645 1.50470376 0.91636765]] [[0.61484962 0.66299872 0.53258442]
 [0.56390455 0.5758349  0.5043055 ]
 [0.58766876 0.81827498 0.71430141]] [[-0.15552595]
 [-0.18629699]
 [ 0.00167042]]
Input:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual output:
[[0.92]
 [0.86]
 [0.89]]
[[0.46774385 0.67668635 0.13052266]
 [0.25702388 0.30569823 0.01722242]
 [0.35433645 1.50470376 0.91636765]] [[0.61484962 0.66299872 0.53258442]
 [0.56390455 0.5758349  0.5043055 ]
 [0.58766876 0.81827498 0.71430141]] [[-0.15552595]
 [-0.18629699]
 [ 0.00167042]]
Predicted output:
0
[[0.46774385 0.67668635 0.13052266]
 [0.25702388 0.30569823 0.01722242]
 [0.35433645 1.50470376 0.91636765]] [[0.61484962 

[[0.46774385 0.67668635 0.13052266]
 [0.25702388 0.30569823 0.01722242]
 [0.35433645 1.50470376 0.91636765]] [[0.61484962 0.66299872 0.53258442]
 [0.56390455 0.5758349  0.5043055 ]
 [0.58766876 0.81827498 0.71430141]] [[-0.15552595]
 [-0.18629699]
 [ 0.00167042]]
Predicted output:
0
[[0.46774385 0.67668635 0.13052266]
 [0.25702388 0.30569823 0.01722242]
 [0.35433645 1.50470376 0.91636765]] [[0.61484962 0.66299872 0.53258442]
 [0.56390455 0.5758349  0.5043055 ]
 [0.58766876 0.81827498 0.71430141]] [[-0.15552595]
 [-0.18629699]
 [ 0.00167042]]
Loss:
0.7927


[[0.46774385 0.67668635 0.13052266]
 [0.25702388 0.30569823 0.01722242]
 [0.35433645 1.50470376 0.91636765]] [[0.61484962 0.66299872 0.53258442]
 [0.56390455 0.5758349  0.5043055 ]
 [0.58766876 0.81827498 0.71430141]] [[-0.15552595]
 [-0.18629699]
 [ 0.00167042]]
Input:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual output:
[[0.92]
 [0.86]
 [0.89]]
[[0.46774385 0.67668635 0.13052266]
 [0.25702388 0

 [0.35433645 1.50470376 0.91636765]] [[0.61484962 0.66299872 0.53258442]
 [0.56390455 0.5758349  0.5043055 ]
 [0.58766876 0.81827498 0.71430141]] [[-0.15552595]
 [-0.18629699]
 [ 0.00167042]]
Loss:
0.7927


[[0.46774385 0.67668635 0.13052266]
 [0.25702388 0.30569823 0.01722242]
 [0.35433645 1.50470376 0.91636765]] [[0.61484962 0.66299872 0.53258442]
 [0.56390455 0.5758349  0.5043055 ]
 [0.58766876 0.81827498 0.71430141]] [[-0.15552595]
 [-0.18629699]
 [ 0.00167042]]
Input:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual output:
[[0.92]
 [0.86]
 [0.89]]
[[0.46774385 0.67668635 0.13052266]
 [0.25702388 0.30569823 0.01722242]
 [0.35433645 1.50470376 0.91636765]] [[0.61484962 0.66299872 0.53258442]
 [0.56390455 0.5758349  0.5043055 ]
 [0.58766876 0.81827498 0.71430141]] [[-0.15552595]
 [-0.18629699]
 [ 0.00167042]]
Predicted output:
0
[[0.46774385 0.67668635 0.13052266]
 [0.25702388 0.30569823 0.01722242]
 [0.35433645 1.50470376 0.91636765]] [[0.61484962 

 [0.58766876 0.81827498 0.71430141]] [[-0.15552595]
 [-0.18629699]
 [ 0.00167042]]
Input:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual output:
[[0.92]
 [0.86]
 [0.89]]
[[0.46774385 0.67668635 0.13052266]
 [0.25702388 0.30569823 0.01722242]
 [0.35433645 1.50470376 0.91636765]] [[0.61484962 0.66299872 0.53258442]
 [0.56390455 0.5758349  0.5043055 ]
 [0.58766876 0.81827498 0.71430141]] [[-0.15552595]
 [-0.18629699]
 [ 0.00167042]]
Predicted output:
0
[[0.46774385 0.67668635 0.13052266]
 [0.25702388 0.30569823 0.01722242]
 [0.35433645 1.50470376 0.91636765]] [[0.61484962 0.66299872 0.53258442]
 [0.56390455 0.5758349  0.5043055 ]
 [0.58766876 0.81827498 0.71430141]] [[-0.15552595]
 [-0.18629699]
 [ 0.00167042]]
Loss:
0.7927


[[0.46774385 0.67668635 0.13052266]
 [0.25702388 0.30569823 0.01722242]
 [0.35433645 1.50470376 0.91636765]] [[0.61484962 0.66299872 0.53258442]
 [0.56390455 0.5758349  0.5043055 ]
 [0.58766876 0.81827498 0.71430141]] [[-0.15552595

 [0.35433645 1.50470376 0.91636765]] [[0.61484962 0.66299872 0.53258442]
 [0.56390455 0.5758349  0.5043055 ]
 [0.58766876 0.81827498 0.71430141]] [[-0.15552595]
 [-0.18629699]
 [ 0.00167042]]
Predicted output:
0
[[0.46774385 0.67668635 0.13052266]
 [0.25702388 0.30569823 0.01722242]
 [0.35433645 1.50470376 0.91636765]] [[0.61484962 0.66299872 0.53258442]
 [0.56390455 0.5758349  0.5043055 ]
 [0.58766876 0.81827498 0.71430141]] [[-0.15552595]
 [-0.18629699]
 [ 0.00167042]]
Loss:
0.7927


[[0.46774385 0.67668635 0.13052266]
 [0.25702388 0.30569823 0.01722242]
 [0.35433645 1.50470376 0.91636765]] [[0.61484962 0.66299872 0.53258442]
 [0.56390455 0.5758349  0.5043055 ]
 [0.58766876 0.81827498 0.71430141]] [[-0.15552595]
 [-0.18629699]
 [ 0.00167042]]
Input:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual output:
[[0.92]
 [0.86]
 [0.89]]
[[0.46774385 0.67668635 0.13052266]
 [0.25702388 0.30569823 0.01722242]
 [0.35433645 1.50470376 0.91636765]] [[0.61484962 

 [0.58766876 0.81827498 0.71430141]] [[-0.15552595]
 [-0.18629699]
 [ 0.00167042]]
Predicted output:
0
[[0.46774385 0.67668635 0.13052266]
 [0.25702388 0.30569823 0.01722242]
 [0.35433645 1.50470376 0.91636765]] [[0.61484962 0.66299872 0.53258442]
 [0.56390455 0.5758349  0.5043055 ]
 [0.58766876 0.81827498 0.71430141]] [[-0.15552595]
 [-0.18629699]
 [ 0.00167042]]
Loss:
0.7927


[[0.46774385 0.67668635 0.13052266]
 [0.25702388 0.30569823 0.01722242]
 [0.35433645 1.50470376 0.91636765]] [[0.61484962 0.66299872 0.53258442]
 [0.56390455 0.5758349  0.5043055 ]
 [0.58766876 0.81827498 0.71430141]] [[-0.15552595]
 [-0.18629699]
 [ 0.00167042]]
Input:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual output:
[[0.92]
 [0.86]
 [0.89]]
[[0.46774385 0.67668635 0.13052266]
 [0.25702388 0.30569823 0.01722242]
 [0.35433645 1.50470376 0.91636765]] [[0.61484962 0.66299872 0.53258442]
 [0.56390455 0.5758349  0.5043055 ]
 [0.58766876 0.81827498 0.71430141]] [[-0.15552595

 [ 0.00167042]]
Predicted output:
0
[[0.46774385 0.67668635 0.13052266]
 [0.25702388 0.30569823 0.01722242]
 [0.35433645 1.50470376 0.91636765]] [[0.61484962 0.66299872 0.53258442]
 [0.56390455 0.5758349  0.5043055 ]
 [0.58766876 0.81827498 0.71430141]] [[-0.15552595]
 [-0.18629699]
 [ 0.00167042]]
Loss:
0.7927


[[0.46774385 0.67668635 0.13052266]
 [0.25702388 0.30569823 0.01722242]
 [0.35433645 1.50470376 0.91636765]] [[0.61484962 0.66299872 0.53258442]
 [0.56390455 0.5758349  0.5043055 ]
 [0.58766876 0.81827498 0.71430141]] [[-0.15552595]
 [-0.18629699]
 [ 0.00167042]]
Input:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual output:
[[0.92]
 [0.86]
 [0.89]]
[[0.46774385 0.67668635 0.13052266]
 [0.25702388 0.30569823 0.01722242]
 [0.35433645 1.50470376 0.91636765]] [[0.61484962 0.66299872 0.53258442]
 [0.56390455 0.5758349  0.5043055 ]
 [0.58766876 0.81827498 0.71430141]] [[-0.15552595]
 [-0.18629699]
 [ 0.00167042]]
Predicted output:
0
[[0.46774385 0

 [0.58766876 0.81827498 0.71430141]] [[-0.15552595]
 [-0.18629699]
 [ 0.00167042]]
Predicted output:
0
[[0.46774385 0.67668635 0.13052266]
 [0.25702388 0.30569823 0.01722242]
 [0.35433645 1.50470376 0.91636765]] [[0.61484962 0.66299872 0.53258442]
 [0.56390455 0.5758349  0.5043055 ]
 [0.58766876 0.81827498 0.71430141]] [[-0.15552595]
 [-0.18629699]
 [ 0.00167042]]
Loss:
0.7927


[[0.46774385 0.67668635 0.13052266]
 [0.25702388 0.30569823 0.01722242]
 [0.35433645 1.50470376 0.91636765]] [[0.61484962 0.66299872 0.53258442]
 [0.56390455 0.5758349  0.5043055 ]
 [0.58766876 0.81827498 0.71430141]] [[-0.15552595]
 [-0.18629699]
 [ 0.00167042]]
Input:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual output:
[[0.92]
 [0.86]
 [0.89]]
[[0.46774385 0.67668635 0.13052266]
 [0.25702388 0.30569823 0.01722242]
 [0.35433645 1.50470376 0.91636765]] [[0.61484962 0.66299872 0.53258442]
 [0.56390455 0.5758349  0.5043055 ]
 [0.58766876 0.81827498 0.71430141]] [[-0.15552595

 [0.58766876 0.81827498 0.71430141]] [[-0.15552595]
 [-0.18629699]
 [ 0.00167042]]
Predicted output:
0
[[0.46774385 0.67668635 0.13052266]
 [0.25702388 0.30569823 0.01722242]
 [0.35433645 1.50470376 0.91636765]] [[0.61484962 0.66299872 0.53258442]
 [0.56390455 0.5758349  0.5043055 ]
 [0.58766876 0.81827498 0.71430141]] [[-0.15552595]
 [-0.18629699]
 [ 0.00167042]]
Loss:
0.7927


[[0.46774385 0.67668635 0.13052266]
 [0.25702388 0.30569823 0.01722242]
 [0.35433645 1.50470376 0.91636765]] [[0.61484962 0.66299872 0.53258442]
 [0.56390455 0.5758349  0.5043055 ]
 [0.58766876 0.81827498 0.71430141]] [[-0.15552595]
 [-0.18629699]
 [ 0.00167042]]
Input:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual output:
[[0.92]
 [0.86]
 [0.89]]
[[0.46774385 0.67668635 0.13052266]
 [0.25702388 0.30569823 0.01722242]
 [0.35433645 1.50470376 0.91636765]] [[0.61484962 0.66299872 0.53258442]
 [0.56390455 0.5758349  0.5043055 ]
 [0.58766876 0.81827498 0.71430141]] [[-0.15552595

[[0.46774385 0.67668635 0.13052266]
 [0.25702388 0.30569823 0.01722242]
 [0.35433645 1.50470376 0.91636765]] [[0.61484962 0.66299872 0.53258442]
 [0.56390455 0.5758349  0.5043055 ]
 [0.58766876 0.81827498 0.71430141]] [[-0.15552595]
 [-0.18629699]
 [ 0.00167042]]
Loss:
0.7927


[[0.46774385 0.67668635 0.13052266]
 [0.25702388 0.30569823 0.01722242]
 [0.35433645 1.50470376 0.91636765]] [[0.61484962 0.66299872 0.53258442]
 [0.56390455 0.5758349  0.5043055 ]
 [0.58766876 0.81827498 0.71430141]] [[-0.15552595]
 [-0.18629699]
 [ 0.00167042]]
Input:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual output:
[[0.92]
 [0.86]
 [0.89]]
[[0.46774385 0.67668635 0.13052266]
 [0.25702388 0.30569823 0.01722242]
 [0.35433645 1.50470376 0.91636765]] [[0.61484962 0.66299872 0.53258442]
 [0.56390455 0.5758349  0.5043055 ]
 [0.58766876 0.81827498 0.71430141]] [[-0.15552595]
 [-0.18629699]
 [ 0.00167042]]
Predicted output:
0
[[0.46774385 0.67668635 0.13052266]
 [0.25702388 0